name: state_controllers
description: A small library for keeping widget state and application logic in separate controller classes.
version: 1.0.0
repository: https://github.com/dumabg/state_controllers
homepage: https://github.com/dumabg/state_controllers

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
